### ISSUE TITLE
The downloadable XP tracker is out of date.

### ISSUE THREAD

**Issue by rbwhitaker** [rbwhitaker/CSharpPlayersGuideEarlyAccess#446]
Check these things:

- [x] The page number for The Old Robot challenge.
- [x] The Robotic Interface is not in the XP tracker.
- [x] Removing Carrying Water and replacing it with The Old Robot.

**Comment by rbwhitaker** [comment]
Check these things:

- [ ] The page number for The Old Robot challenge.
- [ ] The Robotic Interface is not in the XP tracker.
- [ ] Removing Carrying Water and replacing it with The Old Robot.
